# Generated by Django 4.1.7 on 2023-04-08 10:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameDlcLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'game_dlc_link',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField(auto_now_add=True, db_index=True)),
                ('developers_uuid', models.UUIDField(db_index=True)),
                ('publishers_uuid', models.UUIDField(db_index=True)),
                ('description', models.TextField()),
                ('about', models.TextField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('adult', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('M', 'MODERATION'), ('P', 'PUBLISH'), ('C', 'CLOSE')], default='M', max_length=2)),
                ('type', models.CharField(choices=[('G', 'GAMES'), ('D', 'ADDITIONS')], max_length=2)),
                ('dlcs', models.ManyToManyField(blank=True, through='core.GameDlcLink', to='core.product')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='SystemRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operating_system', models.CharField(choices=[('L', 'Linux'), ('W', 'Windows'), ('M', 'MacOS'), ('P', 'PlayStation'), ('X', 'XBox')], max_length=2)),
                ('device_processor', models.CharField(max_length=100, verbose_name='Processor')),
                ('device_memory', models.CharField(max_length=100, verbose_name='Memory')),
                ('device_storage', models.CharField(max_length=100, verbose_name='Storage')),
                ('device_graphics', models.CharField(max_length=100, verbose_name='Graphics')),
                ('type_requirements', models.CharField(choices=[('M', 'Minimals'), ('R', 'Recommends')], max_length=2, verbose_name='Min/Rec')),
                ('game', models.ForeignKey(limit_choices_to={'type': 'G'}, on_delete=django.db.models.deletion.CASCADE, related_name='system_requirements', to='core.product')),
            ],
            options={
                'db_table': 'system_requirement',
            },
        ),
        migrations.AddField(
            model_name='gamedlclink',
            name='dlc',
            field=models.ForeignKey(limit_choices_to={'type': 'D'}, on_delete=django.db.models.deletion.CASCADE, related_name='game_link', to='core.product'),
        ),
        migrations.AddField(
            model_name='gamedlclink',
            name='game',
            field=models.ForeignKey(limit_choices_to={'type': 'G'}, on_delete=django.db.models.deletion.CASCADE, related_name='dlc_link', to='core.product'),
        ),
        migrations.AddConstraint(
            model_name='gamedlclink',
            constraint=models.UniqueConstraint(fields=('dlc',), name='unique_dlc_game'),
        ),
    ]
