# Generated by Django 4.1.7 on 2023-04-09 13:17

import uuid

import apps.base.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payment_accounts', '0002_rename_user_uid_account_user_uuid_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='item_uid',
            new_name='item_uuid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='developer_account',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='transactions',
                to='payment_accounts.account',
            ),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item_price',
            field=apps.base.fields.MoneyField(
                decimal_places=2,
                max_digits=11,
                validators=[
                    django.core.validators.MinValueValidator(0, message='Should be positive value'),
                    django.core.validators.MaxValueValidator(
                        10000,
                        message='Should be not greater than 10000',
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='amount',
            field=apps.base.fields.MoneyField(
                decimal_places=2,
                editable=False,
                max_digits=11,
                validators=[
                    django.core.validators.MinValueValidator(0, message='Should be positive value'),
                ],
            ),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                (
                    'invoice_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('transactions', models.ManyToManyField(to='transactions.transaction')),
            ],
        ),
    ]
