# Generated by Django 4.1.7 on 2023-05-02 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("developer", "0002_remove_companyuser_date_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyuser",
            name="last_login",
        ),
    ]
