# Generated by Django 4.1.7 on 2023-04-27 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('developer', '0002_alter_companyuser_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Department name')),
            ],
            options={
                'verbose_name': 'Company department',
                'verbose_name_plural': 'Company department',
            },
        ),
        migrations.AlterUniqueTogether(
            name='developercontenttype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='companycontact',
            options={'verbose_name': 'Company contact', 'verbose_name_plural': 'Company contacts'},
        ),
        migrations.AlterModelOptions(
            name='developerpermission',
            options={'ordering': ['codename'], 'verbose_name': 'Developer permission', 'verbose_name_plural': 'Developer permissions'},
        ),
        migrations.AlterUniqueTogether(
            name='developerpermission',
            unique_together={('codename',)},
        ),
        migrations.RemoveField(
            model_name='companycontact',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='developergroup',
            name='permissions',
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.ManyToManyField(blank=True, related_name='contact_set', related_query_name='contact', through='developer.CompanyContact', to='common.contacttype', verbose_name='Company contact'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.contacttype', verbose_name='type contact'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='value',
            field=models.CharField(default='', max_length=150, verbose_name='value contact'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.company'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Developer avatar'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_user_this_company', to='developer.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.country', verbose_name='Developer country'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='developer_set', related_query_name='developer', to='developer.developergroup', verbose_name='developer_groups'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Developer phone-number'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this developer.', related_name='developer_permission_set', related_query_name='developer_permission', to='developer.developerpermission', verbose_name='developer permissions'),
        ),
        migrations.AlterModelTable(
            name='developerpermission',
            table='Developer permission',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactType',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.company', verbose_name='Company'),
        ),
        migrations.RemoveField(
            model_name='developerpermission',
            name='content_type',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.department', verbose_name='Department'),
        ),
        migrations.DeleteModel(
            name='DeveloperContentType',
        ),
    ]
