# Generated by Django 4.1.7 on 2023-05-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_country_id'),
        ('developer', '0003_remove_companyuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontact',
            name='type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='common.contacttype',
                verbose_name='type contact',
            ),
        ),
    ]
