# Generated by Django 4.1.7 on 2023-05-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_contacttype_options_alter_country_id_and_more"),
        ("developer", "0003_remove_companyuser_last_login"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "company", "verbose_name_plural": "companies"},
        ),
        migrations.AlterModelOptions(
            name="companycontact",
            options={"verbose_name": "company contact", "verbose_name_plural": "company contacts"},
        ),
        migrations.AlterModelOptions(
            name="companyuser",
            options={"verbose_name": "company user", "verbose_name_plural": "company users"},
        ),
        migrations.AlterModelOptions(
            name="developerpermission",
            options={
                "ordering": ["codename"],
                "verbose_name": "developer permission",
                "verbose_name_plural": "developer permissions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="developerpermission",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="companycontact",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.contacttype",
                verbose_name="type contact",
            ),
        ),
        migrations.AlterField(
            model_name="developerpermission",
            name="codename",
            field=models.CharField(max_length=100, unique=True, verbose_name="codename"),
        ),
        migrations.AlterModelTable(
            name="company",
            table="company",
        ),
        migrations.AlterModelTable(
            name="companycontact",
            table="company_contact",
        ),
        migrations.AlterModelTable(
            name="developerpermission",
            table="developer_permission",
        ),
    ]
