# Generated by Django 4.1.7 on 2023-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_alter_developerpermission_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='developerpermission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='developerpermission',
            name='codename',
            field=models.CharField(max_length=100, unique=True, verbose_name='codename'),
        ),
    ]
