# Generated by Django 4.1.7 on 2023-05-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_alter_companycontact_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developerpermission',
            options={
                'ordering': ['codename'],
                'verbose_name': 'developer permission',
                'verbose_name_plural': 'developer permissions',
            },
        ),
        migrations.AlterModelTable(
            name='developerpermission',
            table='developer_permission',
        ),
    ]
