# Generated by Django 4.1.7 on 2023-05-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_alter_developerpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='companycontact',
            options={'verbose_name': 'company contact', 'verbose_name_plural': 'company contacts'},
        ),
        migrations.AlterModelOptions(
            name='companyuser',
            options={'verbose_name': 'company user', 'verbose_name_plural': 'company users'},
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='company_owner',
                to='developer.companyuser',
                verbose_name='company owner',
            ),
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='companycontact',
            table='company_contact',
        ),
    ]
