# Generated by Django 4.2.2 on 2023-06-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("developer", "0005_alter_companyuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
