# Generated by Django 4.1.7 on 2023-06-30 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payment_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='payout_day_of_month',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1,
                        message='The value must be at least 1',
                    ),
                    django.core.validators.MaxValueValidator(
                        28,
                        message='The value should be no more than 28',
                    ),
                ],
            ),
        ),
    ]
