FROM node:18-alpine as build
WORKDIR /app
ADD package.json .
RUN npm i
ADD . .
RUN npm run build

FROM node:18.14.2
WORKDIR .
ADD package.json .
RUN npm i 
# RUN npm i --omit=dev
COPY --from=build app/.next .next
