version: "3"

services:
  frontend_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend_dev
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
