[tool.poetry]
name = "gspot"
version = "0.1.0"
description = ""
authors = ["nikitqa48 <Princen1k@yandex.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

