# Generated by Django 4.1.7 on 2023-03-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_admincontenttype_alter_admin_email_adminpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='admin',
            managers=[
            ],
        ),
    ]
