# Generated by Django 4.1.7 on 2023-05-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacttype",
            options={"verbose_name": "contact_type", "verbose_name_plural": "contact_types"},
        ),
        migrations.AlterField(
            model_name="country",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterModelTable(
            name="contacttype",
            table="contact_type",
        ),
        migrations.CreateModel(
            name='MessageEmailRabbitMQ',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('url', models.CharField()),
                ('text', models.TextField(verbose_name='message_email_rabbitmq')),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('ADMIN_ACTIVATION', 'admin_activation'),
                            ('DEVELOP_ACTIVATION', 'develop_activation'),
                            ('CUSTOMER_ACTIVATION', 'customer_activation'),
                        ],
                    ),
                ),
            ],
            options={
                'verbose_name': 'message_email_rabbitmq',
                'verbose_name_plural': 'message_email_rabbitmq',
                'db_table': 'message_email_rabbitmq',
            },
        ),
        migrations.CreateModel(
            name='MessageNotifyRabbitMQ',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField(verbose_name='message_notify_rabbitmq')),
                ('action', models.CharField(choices=[('ADD_FRIEND', 'add_friend')])),
            ],
            options={
                'verbose_name': 'message_notify_rabbitmq',
                'verbose_name_plural': 'message_notify_rabbitmq',
                'db_table': 'message_notify_rabbitmq',
            },
        ),
    ]
