# Generated by Django 4.1.7 on 2023-05-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_country_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacttype',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelTable(
            name='contacttype',
            table='contact_type',
        ),
    ]
