# Generated by Django 4.2.2 on 2023-06-28 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0003_messageemailrabbitmq_messagenotifyrabbitmq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagenotifyrabbitmq',
            name='url',
        ),
    ]
