version: "3.9"

services:
  web_users_tests:
    container_name: users-service-test
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env.tests
    command: python manage.py test
  db:
    container_name: users-service-db
    image: postgres:14-alpine
    env_file:
      - ../.env.example
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUAL_HOST=/

