version: "3.9"

services:
  web_users:
    env_file:
      - .env
    ports:
      - "8000:8000"
  web_users_tests:
    container_name: users-service-tests
    env_file:
      - .env.tests
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python manage.py test
    depends_on:
      - db
      - rabbitmq
  db:
    env_file:
      - .env
    ports:
      - "5432:5432"
  rabbitmq:
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
