version: "3.9"

services:
  web_users_tests:
    build: ./
    env_file:
      - .env.tests
    restart: "no"
    command: >
      sh -c "python manage.py test"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    extends:
      file: docker-compose.yml
      service: db
    container_name: users-service-db-tests
    env_file:
      - .env.tests
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: users-service-rabbitmq
    expose:
      - 5672
      - 15672
    env_file:
      - .env.tests
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  redis:
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_LOCAL_PASSWORD"
    image: redis:7.0.5-alpine
    expose:
      - 6379
    env_file:
      - .env.tests
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
