version: "3.9"

services:

  redis:
    container_name: channels_redis
    image: redis:7.0
    ports:
      - "6379:6379"

  mongodb:
    container_name: channels_db
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - /mongodb_data:/data/db
    env_file:
      - .env.dev
    networks:
      - mongodb_net
      - rabbitmq_net

  consumer:
    container_name: channels_consumer
    build:
      context: broker
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.dev
    volumes:
      - ./broker:/app
    command: >
      sh -c "python main.py"
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - mongodb_net
      - rabbitmq_net

  rabbitmq:
    image: rabbitmq:3.9
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - .env.dev
    environment:
      RABBITMQ_DEFAULT_USER: ${BROKER_USER}
      RABBITMQ_DEFAULT_PASS: ${BROKER_PASSWORD}
      RABBITMQ_DEFAULT_PORT: ${BROKER_PORTS}
      RABBITMQ_DEFAULT_VHOST: ${BROKER_VHOST}
    ports:
      - "${BROKER_PORTS}:${BROKER_PORTS}"
    networks:
      - rabbitmq_net

  chat:
    container_name: channels_chat
    build:
      context: chat
      dockerfile: Dockerfile
    command: >
      sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    restart: always
    env_file:
      - .env.dev
    volumes:
      - ./chat:/chat/
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started

networks:
  mongodb_net:
  rabbitmq_net:

volumes:
  mongodb_data:
