version: "3.9"

services:

  redis:
    container_name: channels_redis
    image: redis:7.0
    ports:
      - "6379:6379"

  mongodb:
    container_name: channels_db
    image: mongo:6.0
    ports:
      - "27017:27017"
#    volumes:
#      - ./mongo-volume:/data/db
    command: mongod --bind_ip 0.0.0.0
    env_file:
      - .env.dev
    networks:
      - rabbitmq_net

  consumer:
    container_name: channels_consumer
    build:
      context: ./src/broker
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.dev
    volumes:
      - ./src/broker:/app
    command: >
      sh -c "python main.py"
    networks:
      - rabbitmq_net
    depends_on:
      - mongodb

networks:
  rabbitmq_net:
    external: true

#  channels:
#    container_name: fastapi_channels
#    build:
#      context: .
#      dockerfile: ./src/Dockerfile
#    restart: always
##    volumes:
##      - ./src:/app
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env.dev
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#      mongodb:
#        condition: service_started
#      redis:
#        condition: service_started

volumes:
  mongodb_data:
