version: "3.9"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.11.11-management
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5672:5672"
      - "15672:15672"

  channels:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    restart: always
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - mongodb
      - redis
      - rabbitmq

  consumer:
    build:
      context: .
      dockerfile: ./pika/Dockerfile
    restart: always
    volumes:
      - ./pika:/app
    env_file:
      - .env.dev
    depends_on:
      - rabbitmq

volumes:
  mongodb_data:
