version: "3.9"

services:
  mongodb:
    container_name: mongodb_channels
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    container_name: redis_channels
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq_channels
    image: rabbitmq:3.11.11-management
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  channels:
    container_name: fastapi_channels
    build:
      context: .
      dockerfile: ./src/Dockerfile
    restart: always
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started

  consumer:
    build:
      context: .
      dockerfile: ./src/pika/Dockerfile
    restart: always
    volumes:
      - ./src:/app
    env_file:
      - .env.dev
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  mongodb_data:
