# Generated by Django 4.1.7 on 2023-05-30 18:29
import apps.base.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('payment_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentService',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCommission',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('payment_type', models.CharField(max_length=50, verbose_name='type_of_payment')),
                (
                    'commission',
                    apps.base.fields.CommissionField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0,
                                message='Should be positive value',
                            ),
                            django.core.validators.MaxValueValidator(
                                100,
                                message='Should be not greater than 100',
                            ),
                        ],
                    ),
                ),
                (
                    'payment_service_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='external_payments.paymentservice',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='BalanceServiceMap',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('payment_id', models.CharField(editable=False, max_length=70)),
                (
                    'operation_type',
                    models.CharField(choices=[('PO', 'PAYOUT'), ('PM', 'PAYMENT')], max_length=20),
                ),
                (
                    'balance_change_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='payment_accounts.balancechange',
                    ),
                ),
                (
                    'service_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='external_payments.paymentservice',
                    ),
                ),
            ],
        ),
    ]
