# Generated by Django 4.1.7 on 2023-06-25 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('external_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentcommission',
            unique_together={('payment_service_id', 'payment_type')},
        ),
    ]
