import os


REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT')
REDIS_ACCESS_DB = os.getenv('REDIS_ACCESS_DB')
REDIS_REFRESH_DB = os.getenv('REDIS_REFRESH_DB')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD')
REDIS_ACCESS_KEY = os.getenv('REDIS_ACCESS_KEY')
REDIS_REFRESH_KEY = os.getenv('REDIS_REFRESH_KEY')
REDIS_BLACK_LIST_KEY = os.getenv('REDIS_BLACK_LIST_KEY')
