version: "3.9"

services:
  web_users:
    container_name: users-service
    build:
      context: ./..
      dockerfile: docker/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE
    env_file:
      - ../.env.example
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static:/code/static
      - media:/code/media
    restart: always
    expose:
      - 8000
    ports:
      - "8000:8000"
  web_users_tests:
   container_name: users-service-test
   build:
     context: ./..
     dockerfile: docker/python/Dockerfile
   env_file:
     - ../.env.example
   command: python manage.py test
  web_users_admin:
    container_name: users-service-admin
    build:
      context: ./..
      dockerfile: docker/python/Dockerfile
    env_file:
      - ../.env.example
    command: python manage.py createsuperuser --noinput
  db:
    container_name: users-service-db
    image: postgres:14-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ../.env.example
    ports:
      - "5432:5432"

volumes:
  media:
  static:
  pgdata:
