version: "3.9"

services:
  web_users:
    container_name: users-service
    build:
      context: ./..
      dockerfile: docker/python/Dockerfile
    env_file:
      - ../.env
    command: /start-web.sh
    volumes:
      - static:/code/static
      - media:/code/media
    restart: always
    expose:
      - 8000
    ports:
      - "8000:8000"
  db:
    container_name: users-service-db
    image: postgres:14-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5432:5432"

volumes:
  media:
  static:
  pgdata:
