from datetime import timedelta
from decimal import Decimal

MAX_BALANCE_DIGITS = 11
DEFAULT_CURRENCY = 'RUB'
SUPPORTED_CURRENCIES = (DEFAULT_CURRENCY,)
CURRENCIES = (*SUPPORTED_CURRENCIES, 'USD', 'EUR')
MAX_COMMISSION_VALUE = Decimal(100)
PERIOD_FOR_MYSELF_TASK = timedelta(days=1)
PERIOD_FOR_GIFT_TASK = timedelta(days=7)
MINIMUM_PAYOUT_AMOUNT = Decimal(500)
MAXIMUM_YOOKASSA_PAYOUT = Decimal(500000)
MAXIMUM_PAYOUT_AMOUNTS = 1
MAXIMUM_PAYOUTS_PER_MONTH = 1
