# Generated by Django 4.1.7 on 2023-04-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.UUIDField(unique=True, verbose_name='UUID creator')),
                ('is_gift', models.CharField(choices=[('True', True), ('False', False)], max_length=10)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.cart')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.offer')),
            ],
            options={
                'db_table': 'cart_offer',
            },
        ),
    ]
