# Generated by Django 4.1.7 on 2023-04-14 11:07

import base.model_fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_historicalschedulerprice_historicalsale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrderStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING_PAYMENT', 'Waiting Payment'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUNDED', 'Refunded')], default='WAITING_PAYMENT', max_length=16, verbose_name='Status')),
                ('from_dttm', models.DateTimeField(blank=True, editable=False, verbose_name='From dttm')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.order')),
            ],
            options={
                'verbose_name': 'historical order status',
                'verbose_name_plural': 'historical order statuss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrderOfferProduct',
            fields=[
                ('product_id', models.UUIDField(db_index=True, verbose_name='Product UUID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order offer product',
                'verbose_name_plural': 'historical order offer products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrderOffer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('offer_id', models.UUIDField(verbose_name='Offer ID')),
                ('price_currency', models.CharField(choices=[('RUB', 'Rub'), ('USD', 'Usd'), ('KZT', 'Kzt'), ('EUR', 'Eur')], default='RUB', max_length=3, verbose_name='Currency')),
                ('price_amount', base.model_fields.AmountField(decimal_places=2, max_digits=10, verbose_name='Price Amount')),
                ('sale_discount', models.PositiveSmallIntegerField(verbose_name='Total Discount (%)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.order')),
            ],
            options={
                'verbose_name': 'historical order offer',
                'verbose_name_plural': 'historical order offers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_by', models.UUIDField(verbose_name='Created By UUID')),
                ('currency', models.CharField(choices=[('RUB', 'Rub'), ('USD', 'Usd'), ('KZT', 'Kzt'), ('EUR', 'Eur')], default='RUB', max_length=3, verbose_name='Currency')),
                ('total_amount', base.model_fields.AmountField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('total_discount', models.PositiveSmallIntegerField(verbose_name='Total Discount (%)')),
                ('payment_amount', base.model_fields.AmountField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('payment_id', models.CharField(max_length=128, null=True, verbose_name='Payment Id')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('gift_recipient', models.UUIDField(verbose_name='Recipient UUID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order',
                'verbose_name_plural': 'historical orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
