# Generated by Django 4.1.7 on 2023-04-19 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_historicalschedulerprice_historicalsale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.UUIDField(unique=True)),
                ('is_gift', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_offers', to='finance.cart')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_offers', to='finance.offer')),
            ],
            options={
                'db_table': 'cart_offer',
            },
        ),
    ]
