# Generated by Django 4.1.7 on 2023-04-14 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField(unique=True, verbose_name='User')),
                ('games_count', models.PositiveBigIntegerField(default=0)),
                ('dlc_count', models.PositiveBigIntegerField(default=0)),
                ('total_product_count', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'library',
            },
        ),
        migrations.CreateModel(
            name='LibraryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.library')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='products',
            field=models.ManyToManyField(related_name='library', through='finance.LibraryProduct', to='core.product'),
        ),
    ]
