# Generated by Django 4.1.7 on 2023-05-31 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalsystemrequirement_historicalproduct'),
        ('finance', '0003_cart_cartoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField(unique=True, verbose_name='User')),
                ('games_count', models.PositiveIntegerField(default=0, verbose_name='Games counter')),
                ('dlc_count', models.PositiveIntegerField(default=0, verbose_name='DLC counter')),
                ('total_product_count', models.PositiveIntegerField(default=0, verbose_name='Total product counter')),
            ],
            options={
                'db_table': 'library',
            },
        ),
        migrations.CreateModel(
            name='LibraryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_return', models.BooleanField(default=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.library')),
            ],
            options={
                'db_table': 'library_product',
            },
        ),
        migrations.RemoveField(
            model_name='historicalorderoffer',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorderoffer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='historicalorderofferproduct',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorderstatus',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorderstatus',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderoffer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderoffer',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_gift',
        ),
        migrations.AddField(
            model_name='cart',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='gift_recipient',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='offers',
            field=models.ManyToManyField(related_name='cart', through='finance.CartOffer', to='finance.offer'),
        ),
        migrations.AlterField(
            model_name='historicaloffer',
            name='created_by',
            field=models.UUIDField(verbose_name='UUID creator'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_by',
            field=models.UUIDField(verbose_name='UUID creator'),
        ),
        migrations.DeleteModel(
            name='HistoricalOrder',
        ),
        migrations.DeleteModel(
            name='HistoricalOrderOffer',
        ),
        migrations.DeleteModel(
            name='HistoricalOrderOfferProduct',
        ),
        migrations.DeleteModel(
            name='HistoricalOrderStatus',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderOffer',
        ),
        migrations.DeleteModel(
            name='OrderOfferProduct',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.AddField(
            model_name='libraryproduct',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.offer'),
        ),
        migrations.AddField(
            model_name='libraryproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='library',
            name='products',
            field=models.ManyToManyField(related_name='library', through='finance.LibraryProduct', to='core.product'),
        ),
    ]
