# Generated by Django 4.1.7 on 2023-04-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_delete_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpermission',
            options={'ordering': ['codename'], 'verbose_name': 'permission', 'verbose_name_plural': 'permissions'},
        ),
        migrations.AlterUniqueTogether(
            name='adminpermission',
            unique_together={('codename',)},
        ),
        migrations.RemoveField(
            model_name='admingroup',
            name='permissions',
        ),
        migrations.AddField(
            model_name='admin',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='admingroup',
            name='permission',
            field=models.ManyToManyField(blank=True, to='administrator.adminpermission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this admin.', related_name='admin_set', related_query_name='admin', to='administrator.adminpermission', verbose_name='admin permissions'),
        ),
        migrations.AlterModelTable(
            name='adminpermission',
            table='permission',
        ),
        migrations.RemoveField(
            model_name='adminpermission',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='AdminContentType',
        ),
    ]
