# Generated by Django 4.1.7 on 2023-05-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_contacttype_options_alter_country_id_and_more"),
        ("administrator", "0003_remove_admin_last_login"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminpermission",
            options={
                "ordering": ["codename"],
                "verbose_name": "admin_permission",
                "verbose_name_plural": "admin_permissions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="adminpermission",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="admin",
            name="user_permission",
        ),
        migrations.AlterField(
            model_name="admin",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.country",
                verbose_name="admin country",
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this admin.",
                related_name="admin_set",
                related_query_name="admin",
                to="administrator.adminpermission",
                verbose_name="admin permissions",
            ),
        ),
        migrations.AlterField(
            model_name="adminpermission",
            name="codename",
            field=models.CharField(max_length=100, unique=True, verbose_name="codename"),
        ),
        migrations.AlterModelTable(
            name="adminpermission",
            table="admin_permission",
        ),
    ]
