# Generated by Django 4.1.7 on 2023-05-05 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('administrator', '0003_remove_admin_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpermission',
            options={
                'ordering': ['codename'],
                'verbose_name': 'admin_permission',
                'verbose_name_plural': 'admin_permissions',
            },
        ),
        migrations.AlterField(
            model_name='admin',
            name='country',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='common.country',
                verbose_name='admin country',
            ),
        ),
        migrations.AlterModelTable(
            name='adminpermission',
            table='admin_permission',
        ),
    ]
