# Generated by Django 4.1.7 on 2023-06-10 17:13

import administrator.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('administrator', '0004_alter_adminpermission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='admin',
            managers=[
                ('objects', administrator.models.AdminManager()),
            ],
        ),
    ]
