# Generated by Django 4.1.7 on 2023-05-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_remove_admin_user_permission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminpermission',
            table='admin_permission',
        ),
    ]
