# Generated by Django 4.2.2 on 2023-06-13 15:20

import administrator.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0004_alter_customeruser_managers"),
        ("administrator", "0004_alter_adminpermission_options_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="admin",
            managers=[
                ("objects", administrator.models.AdminManager()),
            ],
        ),
        migrations.CreateModel(
            name="BlockReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255, verbose_name="block reason")),
                ("blocked_at", models.DateTimeField(auto_now_add=True, verbose_name="block time")),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_reasons",
                        to="customer.customeruser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block reason",
                "verbose_name_plural": "Block reasons",
                "db_table": "block_reasons",
            },
        ),
    ]
