# Generated by Django 4.1.7 on 2023-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_remove_admin_user_permission_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminpermission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='adminpermission',
            name='codename',
            field=models.CharField(max_length=100, unique=True, verbose_name='codename'),
        ),
    ]
