# Generated by Django 4.1.7 on 2023-06-17 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('administrator', '0005_alter_admin_managers'),
        ('administrator', '0005_alter_admin_managers_blockreason'),
    ]

    operations = []
