# Generated by Django 4.2.2 on 2023-06-28 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('administrator', '0006_merge_20230617_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockreason',
            name='reason',
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name='block reason',
            ),
        ),
    ]
