# Generated by Django 4.2.2 on 2023-07-01 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('administrator', '0007_admin_is_staff'),
        ('administrator', '0007_alter_blockreason_reason'),
    ]

    operations = []
