# Generated by Django 4.2.2 on 2023-07-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('administrator', '0007_admin_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymoderate',
            name='action',
            field=models.CharField(choices=[('U', 'Unblock'), ('B', 'Block')], max_length=1),
        ),
        migrations.AlterField(
            model_name='companyusermoderate',
            name='action',
            field=models.CharField(choices=[('U', 'Unblock'), ('B', 'Block')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customermoderate',
            name='action',
            field=models.CharField(choices=[('U', 'Unblock'), ('B', 'Block')], max_length=1),
        ),
    ]
