# Generated by Django 4.2.2 on 2023-07-17 19:14

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0008_alter_companymoderate_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=base.utils.get_avatar_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="companymoderate",
            name="action",
            field=models.CharField(choices=[("B", "Block"), ("U", "Unblock")], max_length=1),
        ),
        migrations.AlterField(
            model_name="companyusermoderate",
            name="action",
            field=models.CharField(choices=[("B", "Block"), ("U", "Unblock")], max_length=1),
        ),
        migrations.AlterField(
            model_name="customermoderate",
            name="action",
            field=models.CharField(choices=[("B", "Block"), ("U", "Unblock")], max_length=1),
        ),
    ]
