# Generated by Django 4.1.7 on 2023-04-17 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gamedlclink_dlc_alter_gamedlclink_game_and_more'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('GAME_LOGO', 'Game Logo'), ('PHOTO_SLIDER', 'Photo Slider')], max_length=12, verbose_name='Media_file'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='like_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=7, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=7, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='social',
            name='product',
            field=models.ForeignKey(limit_choices_to={'type': 'GAMES'}, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='core.product'),
        ),
        migrations.AlterField(
            model_name='social',
            name='type',
            field=models.CharField(choices=[('FACEBOOK', 'FaceBook'), ('VKONTAKTE', 'VKontakte'), ('SITE', 'Site'), ('YOUTUBE', 'YouTube'), ('TWITTER', 'Twitter'), ('TWITCH', 'Twitch'), ('TELEGRAM', 'Telegram')], default='SITE', max_length=9, verbose_name='Social_media'),
        ),
    ]
