# Generated by Django 4.1.7 on 2023-04-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_historicalsocial_historicalreview_historicalreaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmedia',
            name='type',
            field=models.CharField(choices=[('GAME_LOGO', 'Game Logo'), ('PHOTO_SLIDER', 'Photo Slider')], max_length=12, verbose_name='Media_file'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('GAME_LOGO', 'Game Logo'), ('PHOTO_SLIDER', 'Photo Slider')], max_length=12, verbose_name='Media_file'),
        ),
    ]
