# Generated by Django 4.2.2 on 2023-07-17 17:34

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0004_alter_customeruser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeruser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=base.models.avatar_upload_path
            ),
        ),
    ]
