# Generated by Django 4.1.7 on 2023-04-10 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('reference', '0001_initial'), ('reference', '0002_alter_subgenre_name'), ('reference', '0003_alter_genreproduct_genre'), ('reference', '0004_alter_language_options_alter_productlanguage_options_and_more'), ('reference', '0005_alter_genre_table_alter_subgenre_table')]

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование языка', max_length=100, verbose_name='Наименование языка')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Поджанр для продукта')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgenres', to='reference.genre')),
            ],
        ),
        migrations.CreateModel(
            name='SubgenreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('subgenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.subgenre')),
            ],
        ),
        migrations.AddField(
            model_name='subgenre',
            name='products',
            field=models.ManyToManyField(related_name='subgenres', through='reference.SubgenreProduct', to='core.product'),
        ),
        migrations.CreateModel(
            name='ProductLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.BooleanField(default=True, verbose_name='Интерфейс')),
                ('subtitles', models.BooleanField(default=True, verbose_name='Титры')),
                ('voice', models.BooleanField(default=True, verbose_name='Озвучка')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_supported_language', to='reference.language')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='core.product')),
            ],
            options={
                'verbose_name': 'Поддерживаемый язык',
                'verbose_name_plural': 'Поддерживаемые языки',
            },
        ),
        migrations.CreateModel(
            name='GenreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.genre')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='products',
            field=models.ManyToManyField(related_name='genres', through='reference.GenreProduct', to='core.product'),
        ),
        migrations.AddConstraint(
            model_name='subgenre',
            constraint=models.UniqueConstraint(fields=('name', 'genre'), name='unique_genre_subgenre'),
        ),
        migrations.AddConstraint(
            model_name='productlanguage',
            constraint=models.UniqueConstraint(fields=('language', 'product'), name='unique_language_game'),
        ),
        migrations.AlterField(
            model_name='subgenre',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Subgenre'),
        ),
        migrations.AlterField(
            model_name='genreproduct',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.genre'),
        ),
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productlanguage',
            options={},
        ),
        migrations.AlterField(
            model_name='genreproduct',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference.genre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productlanguage',
            name='interface',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productlanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='reference.language'),
        ),
        migrations.AlterField(
            model_name='productlanguage',
            name='subtitles',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productlanguage',
            name='voice',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='language',
            table='language',
        ),
        migrations.AlterModelTable(
            name='productlanguage',
            table='product_language',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
        migrations.AlterModelTable(
            name='subgenre',
            table='subgenre',
        ),
    ]
