# Generated by Django 4.1.7 on 2023-04-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gamedlclink_dlc_alter_gamedlclink_game_and_more'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='genre',
            name='unique_genre',
        ),
        migrations.RemoveConstraint(
            model_name='subgenreproduct',
            name='unique_genre_game',
        ),
        migrations.RemoveField(
            model_name='subgenreproduct',
            name='genre',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='subgenre',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Subgenre'),
        ),
        migrations.AlterField(
            model_name='subgenre',
            name='products',
            field=models.ManyToManyField(related_name='subgenres', through='reference.SubgenreProduct', to='core.product'),
        ),
        migrations.AlterField(
            model_name='subgenreproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='subgenreproduct',
            name='subgenre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.subgenre'),
        ),
        migrations.AlterModelTable(
            name='subgenre',
            table='subgenre',
        ),
        migrations.AlterModelTable(
            name='subgenreproduct',
            table=None,
        ),
        migrations.AddField(
            model_name='genreproduct',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.genre'),
        ),
        migrations.AddField(
            model_name='genreproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='products',
            field=models.ManyToManyField(related_name='genres', through='reference.GenreProduct', to='core.product'),
        ),
    ]
