# Generated by Django 4.1.7 on 2023-05-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_historicalsubgenre_historicalproductlanguage_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='genreproduct',
            constraint=models.UniqueConstraint(fields=('product', 'genre'), name='unique_genre_product'),
        ),
        migrations.AddConstraint(
            model_name='subgenreproduct',
            constraint=models.UniqueConstraint(fields=('product', 'subgenre'), name='unique_subgenre_product'),
        ),
        migrations.AlterModelTable(
            name='genreproduct',
            table='genre_product',
        ),
        migrations.AlterModelTable(
            name='subgenreproduct',
            table='subgenre_product',
        ),
    ]
