export { default as GameCard, GameCardBig } from './GameCard'
export { default as Platform } from './Platform'
export { default as FilterGames } from './FilterGames'
export { default as ListGames } from './ListGames'
export { default as Requirements } from './Requirements'
export { default as Languages } from './Languages'
