name: Django CI/CD for games
on:
  push:
    branches: [ "main", "games" ]
  pull_request:
    branches: [ "main", "games" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install flake8
        cd backend/games
        pip install -r requirements.txt
    - name: Test with flake8 and django tests
      run: |
        cd backend/games
        python -m flake8
        python manage.py test
    - name: Build and run containers
      run: |
        cd backend/games && docker-compose up -d --build
